fedora:
    image: registry.gitlab.com/caspermeijn/docker-images/fedora-build-onvifviewer:latest
    stage: build
    script: 
        - cd ..
        - git clone https://github.com/KDAB/KDSoap.git
        - mkdir build-KDSoap
        - cd build-KDSoap/
        - cmake ../KDSoap/ -DCMAKE_INSTALL_PREFIX=/usr/local
        - make
        - make install
        - cd ..
        - mkdir build-kdsoap-ws-discovery-client
        - cd build-kdsoap-ws-discovery-client
        - cmake $CI_PROJECT_DIR 
        - make 
        - make install
